"""
Generates the English variants (*.en.svg) of the Chinese architecture diagrams in assets/diagrams.

The Chinese SVGs are the source of truth. After changing one, add any new strings to the table below and run:
    python3 scripts/translate-diagrams.py assets/diagrams
The script fails when a Chinese string has no translation, so the two variants cannot drift silently.
"""
import re, sys
T = {
'ddk-system-overview': {
'DDK 能力全景':'DDK capability overview',
'DDK 的能力按应用分层排列：adapter 对应 web starter 与统一响应，application 对应分页与对象映射，domain 对应领域模型基类，infrastructure 对应 MyBatis 仓储与各类技术 starter；构建期由 archguard starter 以 ArchUnit 规则守住分层边界。':'DDK capabilities arranged by application layer: adapter gets the web starter and unified responses, application gets pagination and object mapping, domain gets the model primitives, infrastructure gets the MyBatis repository and technical starters; at build time the ArchGuard starter enforces layer boundaries with ArchUnit.',
'DDK 提供哪些能力、分别插在你的哪一层——以及构建期由谁来守住这些边界。':'What DDK provides, where each piece plugs in, and what guards the boundaries.',
'你的应用':'Your application',
'协议适配':'Protocol adapters',
'全局异常处理 · Jackson · CORS':'Global exceptions · Jackson · CORS',
'统一响应结构与错误码契约':'Unified response and error codes',
'用例编排':'Use cases',
'分页入参与结果，页大小有上限':'Paged queries with a page-size cap',
'Entity↔PO 映射注册表，缺失即失败':'Entity↔PO mapper registry, fail-fast',
'业务规则':'Business rules',
'聚合边界、事件收集、Specification':'Aggregates, events, Specification',
'技术实现':'Implementation',
'通用仓储 · 查询解析 · 分页适配':'Generic repository · query parsing · paging',
'5 个基础设施 starter':'Infrastructure starters',
'构建期':'Build time',
'把「adapter 不碰业务、domain 不依赖框架」写成 ArchUnit 测试，违反时构建失败——约束不再只写在文档里。':'"Adapters hold no business logic, the domain depends on no framework" becomes an ArchUnit test that fails the build.',
'未发布到 Maven 中央仓库，当前需要本地 mvn install':'Install locally with scripts/ddk.sh',
},
'ddk-domain-model': {
'DDK 领域模型基类关系':'DDK domain model primitives',
'Identifier 实现 ValueObject 并作为 Entity 标识类型的上界；AggregateRoot 继承 Entity 并收集领域事件；AbstractDomainEvent 实现 DomainEvent；事件经 DomainEventPublisher 在事务提交后发布；Specification 独立可选。':'Identifier implements ValueObject and bounds the Entity ID type; AggregateRoot extends Entity and collects domain events; AbstractDomainEvent implements DomainEvent; events are published after commit by DomainEventPublisher; Specification is independent and optional.',
'领域模型基类':'Domain model primitives',
'三件事：给身份一个类型、区分按值相等与按身份相等、给领域事件一个收集与发布的位置。':'Three jobs: give identity a type, separate value from identity equality, and give domain events a home.',
'接口':'interface',
'按值相等 · 不可变 · 自我校验':'Value-equal · immutable · validated',
'抽象类':'abstract class',
'equals 比较具体类型':'equals compares concrete types',
'toString() 直出原始值':'toString() prints the raw value',
'按身份相等，与字段值无关':'Equal by identity, not by fields',
'hashCode 取 getClass()':'hashCode uses getClass()',
'回填 ID 后仍能从 Set 找回':'Still found in a Set after ID assignment',
'聚合的唯一入口':'The only entry to the aggregate',
'registerEvent(DomainEvent) 登记':'registerEvent(DomainEvent) records',
'drainDomainEvents() 排空':'drainDomainEvents() drains',
'version 乐观锁版本号':'version for optimistic locking',
'ID 的上界':'bounds ID',
'occurredOn 在构造时固定':'occurredOn fixed at construction',
'省掉 occurredOn 样板':'Removes occurredOn boilerplate',
'record 则直接实现接口':'records implement the interface',
'由基础设施层实现':'Implemented by infrastructure',
'订阅方必须用':'Subscribers must use',
'排空后发布':'publish',
'函数式接口':'functional interface',
'and / or / not 组合业务规则':'Compose rules with and / or / not',
'any() / none() 作为归约初值':'any() / none() as reduction seeds',
'内存判定，不会翻译成 SQL':'Evaluated in memory, never SQL',
'与上面几个类没有继承关系，可以单独使用':'Unrelated to the types above; use it on its own',
'包 com.ddk.core.domain · 零框架依赖，由 DomainPackagePurityTest 强制执行':'Package com.ddk.core.domain · zero framework dependencies, enforced by DomainPackagePurityTest',
},
'ddk-module-map': {
'DDK 模块依赖地图':'DDK module dependency map',
'业务应用依赖 starter，starter 依赖 ddk-core；只有 ddk-mybatis-starter 和需要持久化的应用经过 ddk-mybatis；ddk-core 内含 domain、repository、page、mapper、response、exception 六个包。':'Applications depend on starters, starters depend on ddk-core; only ddk-mybatis-starter and applications that persist data go through ddk-mybatis; ddk-core contains the domain, repository, page, mapper, response and exception packages.',
'模块依赖地图':'Module dependency map',
'箭头方向即依赖方向。只有需要持久化的模块才会碰到 ddk-mybatis，其余 starter 直接依赖 ddk-core。':'Arrows point along dependencies. Only persistence touches ddk-mybatis; every other starter depends on ddk-core directly.',
'你的业务应用':'Your application',
'按需引入 starter，版本号由 BOM 统一':'Pick the starters you need; the BOM manages versions',
'依赖':'depends on',
'9 个 Spring Boot starter，统一 ddk.* 配置':'9 Spring Boot starters under one ddk.* namespace',
'全局异常 · Jackson · CORS':'Exceptions · Jackson · CORS',
'分页 · 乐观锁 · 雪花 ID':'Paging · locking · snowflake IDs',
'事务提交后发布领域事件':'Domain events after commit',
'带类型白名单的 JSON':'Allow-listed typed JSON',
'Caffeine + Redis 两级缓存':'Caffeine + Redis two levels',
'按名字注册多数据源':'Named data sources',
'OpenTelemetry · traceId 头':'OpenTelemetry · trace ID header',
'出站调用传播 XID':'Outbound XID propagation',
'ArchUnit 分层规则':'ArchUnit layer rules',
'通用仓储实现 · 查询条件解析 · 分页适配':'Generic repository · query parsing · paging',
'ddk-mybatis-starter 与需要持久化的应用':'ddk-mybatis-starter and persisting apps',
'不依赖任何持久层框架':'No persistence framework',
'com.ddk.core.domain 不得依赖任何框架，这条约束由测试强制执行':'com.ddk.core.domain may not depend on any framework, enforced by tests',
'其余 starter 只依赖 ddk-core':'Other starters only need ddk-core',
'不引入 MyBatis':'and never pull in MyBatis',
'ddk-dependencies（BOM）：下游 import 后无需再写各模块版本号　·　ddk-archetypes：三层 / 四层项目骨架':'ddk-dependencies (BOM): import once, drop module versions   ·   ddk-archetypes: three- and four-layer project skeletons',
},
'ddk-layer-flow': {
'DDK 四层请求流与依赖方向':'DDK four-layer request flow and dependency direction',
'请求依次经过 adapter、application、domain 三层；基础设施层位于领域层之下，通过实现领域层定义的仓储契约反向依赖领域层；领域层反过来依赖基础设施层的边被 ArchUnit 规则禁止。':'A request passes through adapter, application and domain; infrastructure sits below the domain and depends on it by implementing the repository contracts the domain defines; a domain-to-infrastructure dependency is forbidden by ArchUnit rules.',
'一次请求穿过四层':'One request through four layers',
'向内的实线是调用方向，向上的虚线是依赖倒置——领域层定义契约，基础设施层去实现它。':'Solid inward arrows are calls; the dashed upward arrow is dependency inversion: the domain defines contracts and infrastructure implements them.',
'接收 HTTP / MQ 协议':'Receives HTTP / MQ',
'转成 Command、包 ApiResponse':'Builds commands, wraps ApiResponse',
'不写任何业务判断':'No business decisions',
'取出聚合、调用领域方法':'Loads aggregates, calls the domain',
'管事务边界与用例编排':'Owns transactions and orchestration',
'不写业务规则':'No business rules',
'User 聚合根':'User aggregate root',
'不变量与状态机在这里':'Invariants and state live here',
'登记领域事件':'Records domain events',
'不依赖任何框架':'No framework dependencies',
'调用领域方法':'calls',
'① HTTP / MQ 进入':'① HTTP / MQ in',
'返回 UserDTO → ApiResponse':'returns UserDTO → ApiResponse',
'Entity ↔ PO 显式转换':'Explicit Entity ↔ PO mapping',
'保存后排空领域事件':'Drains events after saving',
'实现 domain 定义的':'implements the domain’s',
'仓储契约（依赖倒置）':'repository contract (inversion)',
'被禁止的依赖':'Forbidden dependency',
'领域层不得反过来依赖基础设施':'The domain must not depend on infrastructure',
'一旦 domain 里出现 @Mapper、RedisTemplate 或 PO，':'Once @Mapper, RedisTemplate or a PO shows up in the domain,',
'业务模型就被存储结构绑架，也再不能脱离容器':'the business model is tied to storage and can no longer',
'做单元测试。':'be unit tested without a container.',
'ArchUnit 在构建期拦截':'Blocked by ArchUnit',
'规则来源：CommonArchRules.LAYERED_ARCHITECTURE_RULE 与 DOMAIN_MUST_NOT_DEPEND_ON_FRAMEWORKS':'Rules: CommonArchRules.LAYERED_ARCHITECTURE_RULE and DOMAIN_MUST_NOT_DEPEND_ON_FRAMEWORKS',
},
'ddk-roadmap': {
'DDK 演进路线':'DDK roadmap',
'基础层已完成；v0.1 升级 Spring Boot 4 并发布首个 GitHub Release，v0.2 AI 协作，v0.3 可靠领域事件，v0.4 中间件集成，v1.0 生产就绪；好看又好用贯穿始终。':'The foundation is done; v0.1 moves to Spring Boot 4 and ships the first GitHub Release, v0.2 AI collaboration, v0.3 reliable domain events, v0.4 middleware integrations, v1.0 production ready; looking good and being useful is ongoing.',
'演进路线':'Roadmap',
'基础层已就绪。下一步升级到 Spring Boot 4 并首次发布，随后是 AI 协作、可靠事件与中间件集成。':'The foundation is in place. Next: Spring Boot 4 and a first release, then AI collaboration, reliable events and middleware.',
'基础层':'Foundation',
'已完成':'Done',
'领域模型与仓储':'Domain model',
'9 个 starter':'9 starters',
'archetype 与示例':'Archetypes',
'现代基线':'Modern baseline',
'下一步':'Next',
'JSpecify 空安全':'JSpecify nullness',
'首个 GitHub Release':'GitHub Release',
'AI 协作':'AI collaboration',
'规划中':'Planned',
'代理可读的违规报告':'Agent reports',
'可靠领域事件':'Reliable events',
'事务性 Outbox':'Outbox',
'幂等消费':'Idempotency',
'中间件集成':'Middleware',
'Redisson 聚合锁':'Redisson locks',
'ES 事件读模型':'ES read models',
'生产就绪':'Production ready',
'ddk-mall 参考应用':'ddk-mall app',
'原生镜像 · 虚拟线程':'Native images',
'公开 API 冻结':'Public API freeze',
'贯穿始终':'ONGOING',
'README 首屏动图 · 一行命令创建项目 · 在线项目生成器 · 与 COLA / Spring Modulith 对比 · 每次发布配一篇设计文章':'README demo GIF · one-command project setup · online generator · comparison with COLA / Spring Modulith · a design article per release',
'详见 ROADMAP.zh-CN.md':'See ROADMAP.md',
},
}
root=sys.argv[1]
for name, table in T.items():
    s=open(f'{root}/{name}.svg').read()
    def sub(m):
        t=m.group(3)
        if re.search(r'[一-鿿]', t):
            if t not in table: raise SystemExit(f'{name}: missing {t!r}')
            t=table[t]
        return f'<{m.group(1)}{m.group(2)}>{t}</{m.group(1)}>'
    s=re.sub(r'<(text|title|desc)([^>]*)>(.*?)</\1>', sub, s, flags=re.S)
    left=re.findall(r'[一-鿿]+', s)
    if left: raise SystemExit(f'{name}: leftover {left[:5]}')
    if name=='ddk-roadmap':
        s=s.replace('width="56" height="24"','width="66" height="24"')
    open(f'{root}/{name}.en.svg','w').write(s)
    print('wrote', name)
