# 连接 docker-compose.yml 里的 MySQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: mall
    password: example_password

ddk:
  mybatis:
    db-type: mysql
